env:
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json
extends:
  - '@alex-taxiera/eslint-config-ts'
rules: {}
