oratorOptions:
  defaultPrefix: '>'

statusManagerOptions:
  defaultStatus:
    name: himself
    type: 0

inviteOptions:
  guildId: '165265939389087744'
  channelId: '277471290950942721'

NODE_ENV: development
