name: PR

on:
  - push
  - pull_request

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      -
        run: npm ci
      -
        run: npx tsc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      -
        run: npm ci
      -
        run: npm run lint

  trigger_release:
    name: Trigger Release
    needs: [compile, lint]
    if: github.event == 'push'
    runs-on: ubuntu-latest
    steps:
      -
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.github_token }}
          event-type: release
          client-payload: '{"ref": "${{ github.ref }}", "branch": "${{ steps.extract_branch.outputs.branch }}"}'
