name: Release

on:
  repository_dispatch:
    types: [release]

jobs:
  push_to_docker_hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.client_payload.ref }}
      -
        name: Generate Build Number
        id: build_number
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}
      -
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO }}
          tags: "${{ secrets.NAME }},${{ secrets.NAME }}-${{ steps.build_number.outputs.build_number }},${{ secrets.NAME }}-${{ github.event.client_payload.branch }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
